
set undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap
set backupdir=$XDG_DATA_HOME/vim/backup
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after

if empty(glob('~/.config/vim/autoload/plug.vim'))
  silent !curl -fLo ~/.config/vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

source ~/.dotfiles/vim/autoload/plug.vim
call plug#begin('~/.local/share/vim/plugins')

" General {{{
    abbr funciton function
    abbr teh the
    abbr tempalte template
    abbr fitler filter

    set autoread " detect when a file is changed
    set history=1000 " change history to 1000

    " Searching
    set ignorecase " case insensitive searching
    set smartcase " case-sensitive if expresson contains a capital letter
    set hlsearch " highlight search results
    set incsearch " set incremental search, like modern browsers
    set nolazyredraw " don't redraw while executing macros
" }}}

" Appearance {{{
    set number " show line numbers
    set wrap " turn on line wrapping

    " Tab control
    set smarttab " tab respects 'tabstop', 'shiftwidth', and 'softtabstop'
    set tabstop=4 " the visible width of tabs
    set softtabstop=4 " edit as if the tabs are 4 characters wide
    set shiftwidth=4 " number of spaces to use for indent and unindent
    set shiftround " round indent to a multiple of 'shiftwidth'
    set expandtab "

    " toggle invisible characters
    set list
    set listchars=tab:→\ ,eol:¬,trail:⋅,extends:❯,precedes:❮
    set showbreak=↪

    " Load colorschemes
    Plug 'tomasiser/vim-code-dark'
" }}}

" General Functionality {{{
    " NERDTree {{{
        Plug 'scrooloose/nerdtree'
        Plug 'scrooloose/nerdcommenter'
        Plug 'Xuyuanp/nerdtree-git-plugin'

        " Add spaces after comment delimiters by default
        let g:NERDSpaceDelims = 1
        " Use compact syntax for prettified multi-line comments
        let g:NERDCompactSexyComs = 1
        " Align line-wise comment delimiters flush left instead of following code indentation
        let g:NERDDefaultAlign = 'left'
        " Set a language to use its alternate delimiters by default
        let g:NERDAltDelims_java = 1
        " Add your own custom formats or override the defaults
        let g:NERDCustomDelimiters = { 'c': { 'left': '/**','right': '*/' } }
        " Allow commenting and inverting empty lines (useful when commenting a region)
        let g:NERDCommentEmptyLines = 1
        " Enable trimming of trailing whitespace when uncommenting
        let g:NERDTrimTrailingWhitespace = 1
        " Enable NERDCommenterToggle to check all selected lines is commented or not
        let g:NERDToggleCheckAllLines = 1
        " Don't display these kinds of files
        let NERDTreeIgnore=[ '\.pyc$', '\.pyo$', '\.py\$class$', '\.obj$',
            \ '\.o$', '\.so$', '\.egg$', '^\.git$', '__pycache__', '\.DS_Store' ]
    " }}}

    " FZF {{{
        Plug '/usr/local/opt/fzf'
        Plug 'junegunn/fzf.vim'
        let g:fzf_history_dir = '~/.local/share/fzf-history'
    " }}}
" }}}

" Language-Specific Configuration {{{
    " Asynchronous Lint Engine
    Plug 'w0rp/ale'

    " Linting
    let g:ale_lint_on_save = 1
    let g:ale_linters = {
    \   '*': ['remove_trailing_lines', 'trim_whitespace'],
    \  'python': ['flake8', 'pep8'],
    \}
    " fixing
    let g:ale_fix_on_save = 1
    let g:ale_fixers = {
    \   'python': ['yapf']
    \}
    " Shell {{{
        " Plug 'w0rp/ale'
    " }}}

    " Python {{{
        Plug 'python-mode/python-mode', { 'for': 'python', 'branch': 'develop' }
        Plug 'google/yapf', { 'rtp': 'plugins/vim', 'for': 'python' } " A formatter for Python files
    " }}}

    " JavaScript {{{
        Plug 'posva/vim-vue'
    " }}}

    Plug 'vim-airline/vim-airline'

    " Dockerfile
    Plug 'ekalinin/Dockerfile.vim'

    " Nginx
    " Plug 'nginx/nginx', { 'rtp': 'contrib/vim' }
" }}}

call plug#end()

colorscheme codedark
